#' .. content for \description{} (no empty lines) ..
#'
#' .. content for \details{} ..
#'
#' @title

load_sprint_ndi <- function(outcome) {

  stopifnot(outcome %in% c('acm', 'cvd'))

  data_in <- read_csv("Z:/npajewski/NDI/Data/longterm_death.csv")

  if(outcome == 'acm')
    data_in$status <- data_in$acm_event

  if(outcome == 'cvd')
    data_in$status <- as.numeric(data_in$cvd_event_cr == 1)

  data_selected <- data_in |>
    transmute(
      time = acm_years,
      status,
      intensive,
      sub_senior,
      altdevice,
      hr,
      unable,
      stand_sbp,
      stand_dbp,
      stand_hr,
      dizzy,
      n_agents,
      ACEINH,
      ALDORB,
      ALPBBL,
      ALPHA,
      is_bbl,
      ANG_RB,
      CENTRL,
      DHPCCB,
      DIRVAS,
      KSPDIU,
      LOODIU,
      NDHCCB,
      NI_BBL,
      RENINI,
      THZDIU,
      n_classes,
      liveWithOthers,
      education,
      fulltime,
      Work_FulPrt,
      Insured,
      drugbene,
      atrialFib,
      angina,
      heartAtt,
      conHeartFail,
      irrHeartBeat,
      ulcer,
      crohns,
      diverticulitis,
      hepatitis,
      gallbladder,
      kidinfect,
      BPH,
      prostatitis,
      osteoarthritis,
      rheArthritis,
      gout,
      othArthritis,
      hipprob,
      cancer,
      skinCancer,
      pvd,
      seizure,
      stroke,
      tia,
      thyroidDis,
      anemia,
      diabetes,
      hypertens,
      lowBkPain,
      cataracts,
      schizo,
      depress,
      bipolar,
      anxiety,
      ptsd,
      alcohol,
      CVDFamHst,
      drink_4cat = factor(drink_4cat),
      smoke_pkyrs,
      vigactiv,
      lessvigactiv,
      aspirin,
      othmed,
      egfr,
      screat,
      sub_ckd,
      eGFR_CKDEPI,
      spanishno,
      myocardinfarc,
      acutecorsynd,
      coronaryrevas,
      carotid,
      padrevas,
      stenosis50,
      aaa5repair,
      calcscore400,
      lowabi90,
      lvhcompecg,
      age,
      female,
      sub_cvd,
      race4,
      BUN,
      CHR,
      CL,
      CO2,
      CRDUR,
      GLUR,
      HDL,
      LDLR,
      TRR,
      UMALCR,
      UMALI,
      POTASSIUM,
      age_interview,
      mind,
      moca_complete,
      moca_score_new,
      dsc_total,
      lmir,
      lm_delayed1,
      traila_errors,
      trailatime,
      trailb_errors,
      trailbtime,
      animals_total,
      boston_total,
      hvltir,
      hvlt_trial4,
      hvltp,
      hvlt_true,
      dsforward_total,
      dsbackward_total,
      digitsa,
      copytotal,
      irtotal,
      reypct,
      manfix,
      trigger,
      faq_score,
      faq_deficits,
      distance_m,
      Fortym_flag,
      gait_speed_max,
      gait_speed_mean,
      walkaid = factor(walkaid),
      moca_executive,
      moca_naming,
      moca_attention1,
      moca_attention2,
      moca_attention3,
      moca_language1,
      moca_language2,
      moca_abstraction,
      moca_recall,
      moca_orientation,
      sum_complete_norms,
      ca_impairment1,
      ca_impairment2,
      IIEF_score,
      FESI_score,
      sex_Active,
      FSFI_score,
      EQ5D_index,
      EQ5D_sum,
      PHQ9_score,
      PHQ9_MSDep,
      PHQ9_suicide,
      VR12_PCS,
      VR12_MCS,
      gen_health = factor(gen_health),
      weight,
      height,
      BMI,
      refuMiss,
      antiAnginal,
      nitrate,
      antiArrhythmic,
      nonStatinLL,
      statin,
      alzheimer,
      antiDepressant,
      antiPsychotic,
      analgesic,
      NSAID,
      antiThrombotic,
      antiCoagulant,
      antiRheumatic,
      corticosteroid,
      salycilates,
      CVDagent,
      anitInflam,
      antiPlatelet,
      antiParkinsons,
      vitaminD,
      oralDiabetes,
      antiGout,
      hormones,
      osteoporosis,
      stimulant,
      MMAS_score,
      MMASpoorAdh,
      cystatinc,
      eGFR_CKDEPI_CyC,
      eGFR_CKDEPI_CrCyC,
      sbp,
      dbp,
      InclusionFRS,
      fr_risk10yrs,
      cog_global_v1,
      cog_global_v2,
      cog_memory,
      cog_executive_v1,
      cog_executive_v2,
      cog_attention,
      cog_language,
      fi_new,
      edu_grp_moca,
      moca_status
    )

  too_many_miss <- map_dbl(data_selected, ~mean(is.na(.x))) |>
    enframe() |>
    filter(value >= 0.4) |>
    pull(name)

  data_selected[, too_many_miss] <- NULL

  too_few_unique <-
    map_int(data_selected, ~length(unique(na.omit(.x)))) |>
    enframe() |>
    filter(value == 1) |>
    pull(name)


  data_selected[, too_few_unique] <- NULL

  data_selected


}
